// theme.ts

// 1. import `extendTheme` function
import { extendTheme, ThemeConfig } from '@chakra-ui/react';

// 2. Add your color mode config
const config: ThemeConfig = {
  initialColorMode: 'system',
  useSystemColorMode: false,
};

const styles = {
  global: () => ({
    code: {
      backgroundColor: 'hsla(0, 0%, 0%, 0.04)',
      fontSize: '0.8rem',
      lineHeight: '1.45rem',
    },
    body: {
      margin: '0',
      fontFamily:
        '"Helvetica Neue", Arial, "Hiragino Kaku Gothic ProN", "Hiragino Sans", Meiryo, sans-serif',
      WebkitFontSmoothing: 'antialiased',
      MozOsxFontSmoothing: 'grayscale',
      color: 'hsla(0, 0%, 0%, 0.8)',
      fontWeight: 'normal',
      wordWrap: 'break-word',
      fontKerning: 'normal',
      MozFontFeatureSettings: '"kern", "liga", "clig", "calt"',
      msFontFeatureSettings: '"kern", "liga", "clig", "calt"',
      WebkitFontFeatureSettings: '"kern", "liga", "clig", "calt"',
      fontFeatureSettings: '"kern", "liga", "clig", "calt"',
    },
    'article,\naside,\ndetails,\nfigcaption,\nfigure,\nfooter,\nheader,\nmain,\nmenu,\nnav,\nsection,\nsummary':
      {
        display: 'block',
      },
    'audio,\ncanvas,\nprogress,\nvideo': { display: 'inline-block' },
    'audio:not([controls])': { display: 'none', height: '0' },
    progress: { verticalAlign: 'baseline' },
    '[hidden],\ntemplate': { display: 'none' },
    a: {
      fontStyle: 'normal',
      color: 'hsla(0, 0%, 0%, 0.8)',
      WebkitTextDecorationSkip: 'objects',
    },
    'a:active,\na:hover': { outlineWidth: '0' },
    'abbr[title]': {
      borderBottom: '1px dotted hsla(0, 0%, 0%, 0.5)',
      textDecoration: 'none',
      cursor: 'help',
    },
    'b,\nstrong': { fontWeight: ['inherit', 'bolder'] },
    dfn: { fontStyle: 'italic' },
    h1: {
      fontSize: '2.25rem',
      margin: '0.67em 0',
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
      color: 'inherit',
      fontWeight: 'bold',
      textRendering: 'optimizeLegibility',
      lineHeight: 1.1,
    },
    mark: { backgroundColor: '#ff0', color: '#000' },
    small: { fontSize: '80%' },
    'sub,\nsup': {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
      verticalAlign: 'baseline',
    },
    sub: { bottom: '-0.25em' },
    sup: { top: '-0.5em' },
    img: {
      borderStyle: 'none',
      maxWidth: '100%',
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    'svg:not(:root)': { overflow: 'hidden' },
    'code,\nkbd,\npre,\nsamp': {
      fontFamily: 'monospace, monospace',
      fontSize: '1em',
    },
    figure: {
      margin: '1em 40px',
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    hr: {
      boxSizing: 'content-box',
      height: '1px',
      overflow: 'visible',
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: 'calc(1.45rem - 1px)',
      background: 'hsla(0, 0%, 0%, 0.2)',
      border: 'none',
    },
    'button,\ninput,\noptgroup,\nselect,\ntextarea': {
      font: 'inherit',
      margin: '0',
    },
    optgroup: { fontWeight: 700 },
    'button,\ninput': { overflow: 'visible' },
    'button,\nselect': { textTransform: 'none' },
    '[type="reset"],\n[type="submit"],\nbutton,\nhtml [type="button"]': {
      WebkitAppearance: 'button',
    },
    '[type="button"]::-moz-focus-inner,\n[type="reset"]::-moz-focus-inner,\n[type="submit"]::-moz-focus-inner,\nbutton::-moz-focus-inner':
      {
        borderStyle: 'none',
        padding: '0',
      },
    '[type="button"]:-moz-focusring,\n[type="reset"]:-moz-focusring,\n[type="submit"]:-moz-focusring,\nbutton:-moz-focusring':
      {
        outline: '1px dotted ButtonText',
      },
    fieldset: {
      border: '1px solid silver',
      margin: '0 2px',
      padding: '0.35em 0.625em 0.75em',
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    legend: {
      boxSizing: 'border-box',
      color: 'inherit',
      display: 'table',
      maxWidth: '100%',
      padding: '0',
      whiteSpace: 'normal',
    },
    textarea: { overflow: 'auto' },
    '[type="checkbox"],\n[type="radio"]': {
      boxSizing: 'border-box',
      padding: '0',
    },
    '[type="number"]::-webkit-inner-spin-button,\n[type="number"]::-webkit-outer-spin-button':
      {
        height: 'auto',
      },
    '[type="search"]': { WebkitAppearance: 'textfield', outlineOffset: '-2px' },
    '[type="search"]::-webkit-search-cancel-button,\n[type="search"]::-webkit-search-decoration':
      {
        WebkitAppearance: 'none',
      },
    '::-webkit-input-placeholder': { color: 'inherit', opacity: 0.54 },
    '::-webkit-file-upload-button': {
      WebkitAppearance: 'button',
      font: 'inherit',
    },
    html: {
      font: '112.5%/1.45em georgia, serif',
      boxSizing: 'border-box',
      overflowY: 'scroll',
    },
    '*': { boxSizing: 'inherit' },
    '*:before': { boxSizing: 'inherit' },
    '*:after': { boxSizing: 'inherit' },
    h2: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
      color: 'inherit',
      fontWeight: 'bold',
      textRendering: 'optimizeLegibility',
      fontSize: '1.62671rem',
      lineHeight: 1.1,
    },
    h3: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
      color: 'inherit',
      fontWeight: 'bold',
      textRendering: 'optimizeLegibility',
      fontSize: '1.38316rem',
      lineHeight: 1.1,
    },
    h4: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
      color: 'inherit',
      fontWeight: 'bold',
      textRendering: 'optimizeLegibility',
      fontSize: '1rem',
      lineHeight: 1.1,
    },
    h5: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
      color: 'inherit',
      fontWeight: 'bold',
      textRendering: 'optimizeLegibility',
      fontSize: '0.85028rem',
      lineHeight: 1.1,
    },
    h6: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
      color: 'inherit',
      fontWeight: 'bold',
      textRendering: 'optimizeLegibility',
      fontSize: '0.78405rem',
      lineHeight: 1.1,
    },
    hgroup: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    ul: {
      marginLeft: '1.45rem',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
      listStylePosition: 'outside',
      listStyleImage: 'none',
    },
    ol: {
      marginLeft: '1.45rem',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
      listStylePosition: 'outside',
      listStyleImage: 'none',
    },
    dl: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    dd: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    p: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    pre: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      marginBottom: '1.45rem',
      fontSize: '0.8rem',
      lineHeight: 1.42,
      background: 'hsla(0, 0%, 0%, 0.04)',
      borderRadius: '3px',
      overflow: 'auto',
      wordWrap: 'normal',
      padding: '1.45rem',
    },
    table: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
      fontSize: '1rem',
      lineHeight: '1.45rem',
      borderCollapse: 'collapse',
      width: '100%',
    },
    blockquote: {
      marginLeft: '1.45rem',
      marginRight: '1.45rem',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    form: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    noscript: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    iframe: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    address: {
      marginLeft: '0',
      marginRight: '0',
      marginTop: '0',
      paddingBottom: '0',
      paddingLeft: '0',
      paddingRight: '0',
      paddingTop: '0',
      marginBottom: '1.45rem',
    },
    b: { fontWeight: 'bold' },
    strong: { fontWeight: 'bold' },
    dt: { fontWeight: 'bold' },
    th: { fontWeight: 'bold' },
    li: { marginBottom: 'calc(1.45rem / 2)' },
    'ol li': { paddingLeft: '0' },
    'ul li': { paddingLeft: '0' },
    'li > ol': {
      marginLeft: '1.45rem',
      marginBottom: 'calc(1.45rem / 2)',
      marginTop: 'calc(1.45rem / 2)',
    },
    'li > ul': {
      marginLeft: '1.45rem',
      marginBottom: 'calc(1.45rem / 2)',
      marginTop: 'calc(1.45rem / 2)',
    },
    'blockquote *:last-child': { marginBottom: '0' },
    'li *:last-child': { marginBottom: '0' },
    'p *:last-child': { marginBottom: '0' },
    'li > p': { marginBottom: 'calc(1.45rem / 2)' },
    kbd: { fontSize: '0.8rem', lineHeight: '1.45rem' },
    samp: { fontSize: '0.8rem', lineHeight: '1.45rem' },
    abbr: { borderBottom: '1px dotted hsla(0, 0%, 0%, 0.5)', cursor: 'help' },
    acronym: {
      borderBottom: '1px dotted hsla(0, 0%, 0%, 0.5)',
      cursor: 'help',
    },
    thead: { textAlign: 'left' },
    'td,\nth': {
      textAlign: 'left',
      borderBottom: '1px solid hsla(0, 0%, 0%, 0.12)',
      fontFeatureSettings: '"tnum"',
      MozFontFeatureSettings: '"tnum"',
      msFontFeatureSettings: '"tnum"',
      WebkitFontFeatureSettings: '"tnum"',
      paddingLeft: '0.96667rem',
      paddingRight: '0.96667rem',
      paddingTop: '0.725rem',
      paddingBottom: 'calc(0.725rem - 1px)',
    },
    'th:first-child,\ntd:first-child': { paddingLeft: '0' },
    'th:last-child,\ntd:last-child': { paddingRight: '0' },
    'tt,\ncode': {
      backgroundColor: 'hsla(0, 0%, 0%, 0.04)',
      borderRadius: '3px',
      fontFamily:
        '"SFMono-Regular", Consolas, "Roboto Mono", "Droid Sans Mono",\n    "Liberation Mono", Menlo, Courier, monospace',
      padding: '0',
    },
    'pre code': { background: 'none', lineHeight: 1.42 },
    'code:before,\ncode:after,\ntt:before,\ntt:after': {
      letterSpacing: '-0.2em',
      content: '" "',
    },
    'pre code:before,\npre code:after,\npre tt:before,\npre tt:after': {
      content: '""',
    },
    'h1::selection,\nh2::selection,\nh3::selection,\nh4::selection,\nh5::selection,\nh6::selection,\np::selection,\na::selection':
      {
        background: '#fffa96cc',
      },
    '.gatsby-highlight': {
      backgroundColor: '#1d1f21',
      borderRadius: '0.3em',
      margin: '0.5em 0',
      padding: '1em',
      overflow: 'auto',
    },
    '.gatsby-highlight pre[class*="language-"].line-numbers': {
      padding: '0',
      paddingLeft: '2.8em',
      overflow: 'initial',
    },
    '@media only screen and (max-width: 480px)': { html: { fontSize: '100%' } },
  }),
};

// 3. extend the theme
const theme = extendTheme({
  config,
  styles,
});

export default theme;
