name: Main

on: pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          # path: ~/.cache/yarn
          path: ~/.cache/npm
          # key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          key: ${{ runner.os }}-npm-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
          # restore-keys: ${{ runner.os }}-yarn-
          restore-keys: ${{ runner.os }}-npm-
      - name: Install dependencies
        # run: yarn install --frozen-lockfile --prefer-offline
        run: npm install
      - name: Run format
        # run: yarn format
        run: npm run format
      - name: Check diff
        run: git diff --exit-code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          # path: ~/.cache/yarn
          path: ~/.cache/npm
          # key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          key: ${{ runner.os }}-npm-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
          # restore-keys: ${{ runner.os }}-yarn-
          restore-keys: ${{ runner.os }}-npm-
      - name: Install dependencies
        # run: yarn install --frozen-lockfile --prefer-offline
        run: npm install
      - name: Run test
        # run: yarn test
        run: npm run test
